// Auto-transcribed 2026-08-17 from the reference file C:\SynologyDrive\Teerawat\
// หนังสือรับรองการหักภาษี-ณ-ที่จ่าย.xlsx (sheet "3%") via openpyxl -- every merge range, static
// cell (value/formula, number format, font, alignment) and border side/style on the form, plus
// column widths and row heights, byte-for-byte from the real government form template. This is
// data, not logic -- tawi50Xlsx.js applies it as the static layer, then overwrites the handful of
// dynamic cells (company/employee/amount fields) on top. Regenerate by re-running the extraction
// script against the reference file if the template itself ever changes; don't hand-edit the
// values below except to fix a transcription error.
//
// Known placeholder values baked into CELLS below (all overwritten at render time by
// tawi50Xlsx.js's writeCompanyBlock/writeEmployeeBlock, listed here so a reviewer diffing this
// file against the reference isn't surprised): Q3 book-no ("เล่มที่") is overwritten with '-' (P3
// is the static caption, left alone), Q4/D17 (ลำดับที่/เลขที่) with the employee's employeeNo,
// C7/P7/C9 with the real company name/tax ID/address, C13/P12/P13/C15 with the employee's
// name/ID/address, M24 (tax year) with the real Buddhist-era year, O24/Q24 (amount/tax) with the
// real annual totals, J53/P53 with the real PVD license no/amount, J54/G55/P55 with the real SSO
// amount/employer account/card no, G60 with the real issue date. The reference file's own example
// values (a real prior filing) are never shown to any user -- every one of these cells is
// unconditionally overwritten before the workbook is ever sent to a client. (2026-08-18: this
// comment previously said "P3", corrected -- was describing pre-fix behavior from before the
// round-1 review caught that exact P3-vs-Q3 mixup in tawi50Xlsx.js itself.)
const MERGES = [
  "A1:R1",
  "Q3:R3",
  "Q4:R4",
  "P6:R6",
  "C7:K7",
  "P7:R7",
  "C9:R9",
  "P12:R12",
  "C13:K13",
  "P13:R13",
  "C15:R15",
  "D17:E17",
  "A18:G20",
  "A22:L23",
  "O22:P23",
  "M24:N24",
  "O24:P24",
  "Q24:R24",
  "M25:N25",
  "O25:P25",
  "Q25:R25",
  "M26:N26",
  "O26:P26",
  "Q26:R26",
  "M27:N27",
  "O27:P27",
  "Q27:R27",
  "M28:N28",
  "O28:P28",
  "Q28:R28",
  "M29:N29",
  "O29:P29",
  "Q29:R29",
  "M30:N30",
  "O30:P30",
  "Q30:R30",
  "M31:N31",
  "O31:P31",
  "Q31:R31",
  "M32:N32",
  "O32:P32",
  "Q32:R32",
  "M33:N33",
  "O33:P33",
  "Q33:R33",
  "G34:H34",
  "M34:N34",
  "O34:P34",
  "Q34:R34",
  "M35:N35",
  "O35:P35",
  "Q35:R35",
  "M36:N36",
  "O36:P36",
  "Q36:R36",
  "M37:N37",
  "O37:P37",
  "Q37:R37",
  "M38:N38",
  "O38:P38",
  "Q38:R38",
  "M39:N39",
  "O39:P39",
  "Q39:R39",
  "M40:N40",
  "O40:P40",
  "Q40:R40",
  "M41:N41",
  "O41:P41",
  "Q41:R41",
  "G42:K42",
  "M42:N42",
  "O42:P42",
  "Q42:R42",
  "M43:N43",
  "O43:P43",
  "Q43:R43",
  "M44:N44",
  "O44:P44",
  "Q44:R44",
  "M45:N45",
  "O45:P45",
  "Q45:R45",
  "M46:N46",
  "O46:P46",
  "Q46:R46",
  "E47:K47",
  "M47:N47",
  "O47:P47",
  "Q47:R47",
  "M48:N48",
  "O48:P48",
  "Q48:R48",
  "O49:P49",
  "Q49:R49",
  "B53:I53",
  "J53:K53",
  "N53:O53",
  "P53:Q53",
  "C54:I54",
  "J54:K54",
  "G55:I55",
  "P55:R55",
  "G60:K60",
];

const CELLS = [
  { addr: "A1", value: "ฉบับที่ 1   ( สำหรับผู้ถูกหักภาษี ณ ที่จ่าย ใช้แนบพร้อมกับแบบแสดงรายการภาษี )", numFmt: "General", font: {name:"Leelawadee",size:10.0,bold:false}, align: {h:"left",v:null,wrap:false} },
  { addr: "A2", value: "ฉบับที่ 2   ( สำหรับผู้ถูกหักภาษี ณ ที่จ่าย เก็บไว้เป็นหลักฐาน)", numFmt: "General", font: {name:"Leelawadee",size:10.0,bold:false}, align: {h:"left",v:null,wrap:false} },
  { addr: "A3", value: "หนังสือรับรองการหักภาษี ณ ที่จ่าย", numFmt: "General", font: {name:"Leelawadee",size:14.0,bold:true}, align: {h:"centerContinuous",v:null,wrap:false} },
  { addr: "P3", value: "เล่มที่", numFmt: "General", font: {name:"Leelawadee",size:10.0,bold:false}, align: {h:"right",v:null,wrap:false} },
  { addr: "Q3", value: "ภ.ง.ด.1ก", numFmt: "@", font: {name:"Leelawadee",size:10.0,bold:false}, align: {h:"center",v:null,wrap:false} },
  { addr: "A4", value: "ตามมาตรา  50  ทวิ  แห่งประมวลรัษฎากร", numFmt: "General", font: {name:"Leelawadee",size:11.0,bold:false}, align: {h:"centerContinuous",v:null,wrap:false} },
  { addr: "P4", value: "เลขที่", numFmt: "General", font: {name:"Leelawadee",size:10.0,bold:false}, align: {h:"right",v:null,wrap:false} },
  { addr: "Q4", value: "9", numFmt: "@", font: {name:"Leelawadee",size:10.0,bold:false}, align: {h:"center",v:null,wrap:false} },
  { addr: "A6", value: "ผู้มีหน้าที่หักภาษี  ณ  ที่จ่าย :-", numFmt: "General", font: {name:"Leelawadee",size:11.0,bold:true}, align: {h:null,v:null,wrap:false} },
  { addr: "O6", value: "เลขประจำตัวประชาชน", numFmt: "General", font: {name:"Leelawadee",size:10.0,bold:false}, align: {h:"right",v:null,wrap:false} },
  { addr: "A7", value: "ชื่อ", numFmt: "General", font: {name:"Leelawadee",size:10.0,bold:true}, align: {h:null,v:"center",wrap:false} },
  { addr: "C7", value: "บริษัท โตไซ โบเอคิ ไคชา (ไทยแลนด์) จำกัด", numFmt: "General", font: {name:"Leelawadee",size:10.0,bold:false}, align: {h:"left",v:"center",wrap:false} },
  { addr: "O7", value: "เลขประจำตัวผู้เสียภาษีอากร", numFmt: "General", font: {name:"Leelawadee",size:10.0,bold:false}, align: {h:"right",v:null,wrap:false} },
  { addr: "P7", value: "0105552006771", numFmt: "0", font: {name:"Leelawadee",size:10.0,bold:false}, align: {h:"center",v:null,wrap:false} },
  { addr: "C8", value: "( ให้ระบุว่าเป็น บุคคล นิติบุคคล บริษัท สมาคม หรือ คณะบุคคล )", numFmt: "General", font: {name:"Leelawadee",size:8.0,bold:false}, align: {h:null,v:null,wrap:false} },
  { addr: "A9", value: "ที่อยู่", numFmt: "General", font: {name:"Leelawadee",size:10.0,bold:true}, align: {h:null,v:"center",wrap:false} },
  { addr: "C9", value: "88 อาคารปาโซ่ ชั้น 14 ถนนสีลม แขวงสุริยวงศ์ เขตบางรัก กรุงเทพมหานคร 10500", numFmt: "General", font: {name:"Leelawadee",size:10.0,bold:false}, align: {h:"left",v:"center",wrap:false} },
  { addr: "C10", value: "( ให้ระบุ  เลขที่  ตรอก/ซอย  หมู่ที่  ถนน  ตำบล/แขวง  อำเภอ/เขต  จังหวัด )", numFmt: "General", font: {name:"Leelawadee",size:8.0,bold:false}, align: {h:null,v:null,wrap:false} },
  { addr: "A12", value: "ผู้ถูกหักภาษี  ณ  ที่จ่าย :-", numFmt: "General", font: {name:"Leelawadee",size:11.0,bold:true}, align: {h:null,v:null,wrap:false} },
  { addr: "O12", value: "เลขประจำตัวประชาชน", numFmt: "General", font: {name:"Leelawadee",size:10.0,bold:false}, align: {h:"right",v:null,wrap:false} },
  { addr: "P12", value: "0000000000000", numFmt: "0", font: {name:"Leelawadee",size:10.0,bold:false}, align: {h:"center",v:null,wrap:false} },
  { addr: "A13", value: "ชื่อ", numFmt: "General", font: {name:"Leelawadee",size:10.0,bold:true}, align: {h:null,v:"center",wrap:false} },
  { addr: "C13", value: "-", numFmt: "General", font: {name:"Leelawadee",size:10.0,bold:false}, align: {h:"left",v:"center",wrap:false} },
  { addr: "O13", value: "เลขประจำตัวผู้เสียภาษีอากร", numFmt: "General", font: {name:"Leelawadee",size:10.0,bold:false}, align: {h:"right",v:null,wrap:false} },
  { addr: "C14", value: "( ให้ระบุว่าเป็น บุคคล นิติบุคคล บริษัท สมาคม หรือ คณะบุคคล )", numFmt: "General", font: {name:"Leelawadee",size:8.0,bold:false}, align: {h:null,v:null,wrap:false} },
  { addr: "A15", value: "ที่อยู่", numFmt: "General", font: {name:"Leelawadee",size:10.0,bold:true}, align: {h:null,v:"center",wrap:false} },
  { addr: "C15", value: "-", numFmt: "General", font: {name:"Leelawadee",size:10.0,bold:false}, align: {h:"left",v:"center",wrap:false} },
  { addr: "C16", value: "( ให้ระบุ  เลขที่  ตรอก/ซอย  หมู่ที่  ถนน  ตำบล/แขวง  อำเภอ/เขต  จังหวัด )", numFmt: "General", font: {name:"Leelawadee",size:8.0,bold:false}, align: {h:null,v:null,wrap:false} },
  { addr: "A17", value: "ลำดับที่", numFmt: "General", font: {name:"Leelawadee",size:11.0,bold:false}, align: {h:null,v:null,wrap:false} },
  { addr: "D17", value: 9, numFmt: "General", font: {name:"Leelawadee",size:10.0,bold:false}, align: {h:"center",v:"center",wrap:false} },
  { addr: "F17", value: "ในแบบ", numFmt: "General", font: {name:"Leelawadee",size:11.0,bold:false}, align: {h:null,v:null,wrap:false} },
  { addr: "H17", value: "X", numFmt: "General", font: {name:"Leelawadee",size:10.0,bold:true}, align: {h:"center",v:null,wrap:false} },
  { addr: "I17", value: "(1) ภ.ง.ด. 1ก.", numFmt: "General", font: {name:"Leelawadee",size:10.0,bold:false}, align: {h:null,v:null,wrap:false} },
  { addr: "K17", value: "(2) ภ.ง.ด. 1ก.พิเศษ", numFmt: "General", font: {name:"Leelawadee",size:10.0,bold:false}, align: {h:null,v:null,wrap:false} },
  { addr: "N17", value: "(3) ภ.ง.ด. 2", numFmt: "General", font: {name:"Leelawadee",size:10.0,bold:false}, align: {h:null,v:null,wrap:false} },
  { addr: "P17", value: "(4) ภ.ง.ด. 2ก.", numFmt: "General", font: {name:"Leelawadee",size:10.0,bold:false}, align: {h:null,v:null,wrap:false} },
  { addr: "A18", value: "(ให้สามารถอ้างอิงหรือสอบยันกันได้ระหว่างลำดับที่ตาม หนังสือรับรองฯ กับแบบยื่นรายการภาษีหักที่จ่าย)", numFmt: "General", font: {name:"BrowalliaUPC",size:10.0,bold:false}, align: {h:"center",v:"center",wrap:true} },
  { addr: "I19", value: "(5) ภ.ง.ด. 3", numFmt: "General", font: {name:"Leelawadee",size:10.0,bold:false}, align: {h:null,v:null,wrap:false} },
  { addr: "K19", value: "(6) ภ.ง.ด. 3ก.", numFmt: "General", font: {name:"Leelawadee",size:10.0,bold:false}, align: {h:null,v:null,wrap:false} },
  { addr: "N19", value: "(7) ภ.ง.ด. 53", numFmt: "General", font: {name:"Leelawadee",size:10.0,bold:false}, align: {h:null,v:null,wrap:false} },
  { addr: "A22", value: "ประเภทเงินได้พึงประเมินที่จ่าย", numFmt: "General", font: {name:"Leelawadee",size:12.0,bold:false}, align: {h:"center",v:"center",wrap:false} },
  { addr: "M22", value: "วัน  เดือน", numFmt: "General", font: {name:"Leelawadee",size:10.0,bold:false}, align: {h:"centerContinuous",v:null,wrap:false} },
  { addr: "O22", value: "จำนวนเงินที่จ่าย", numFmt: "General", font: {name:"Leelawadee",size:10.0,bold:false}, align: {h:"center",v:"center",wrap:false} },
  { addr: "Q22", value: "ภาษีที่หัก", numFmt: "General", font: {name:"Leelawadee",size:10.0,bold:false}, align: {h:"centerContinuous",v:null,wrap:false} },
  { addr: "M23", value: "หรือปีภาษี ที่จ่าย", numFmt: "General", font: {name:"Leelawadee",size:10.0,bold:false}, align: {h:"centerContinuous",v:null,wrap:false} },
  { addr: "Q23", value: "และนำส่งไว้", numFmt: "General", font: {name:"Leelawadee",size:10.0,bold:false}, align: {h:"centerContinuous",v:null,wrap:false} },
  { addr: "A24", value: "1.", numFmt: "General", font: {name:"Leelawadee",size:10.0,bold:false}, align: {h:"center",v:"center",wrap:false} },
  { addr: "B24", value: "เงินเดือน ค่าจ้าง เบี้ยเลี้ยง โบนัส ฯลฯ  ตามมาตรา 40 (1)", numFmt: "General", font: {name:"Leelawadee",size:10.0,bold:false}, align: {h:null,v:"center",wrap:false} },
  { addr: "M24", value: 2568, numFmt: "0", font: {name:"Leelawadee",size:10.0,bold:false}, align: {h:"center",v:"center",wrap:false} },
  { addr: "O24", value: 100000, numFmt: "#,##0.00_ ;[Red]\\-\\ #,##0.00_ ;", font: {name:"Leelawadee",size:10.0,bold:false}, align: {h:"center",v:"center",wrap:false} },
  { addr: "Q24", value: 9000, numFmt: "#,##0.00_ ;[Red]\\-\\ #,##0.00_ ;", font: {name:"Leelawadee",size:10.0,bold:false}, align: {h:"center",v:"center",wrap:false} },
  { addr: "A25", value: "2.", numFmt: "General", font: {name:"Leelawadee",size:10.0,bold:false}, align: {h:"center",v:"center",wrap:false} },
  { addr: "B25", value: "ค่าธรรมเนียม  ค่านายหน้า  ฯลฯ  ตามมาตรา 40 (2)", numFmt: "General", font: {name:"Leelawadee",size:10.0,bold:false}, align: {h:null,v:"center",wrap:false} },
  { addr: "A26", value: "3.", numFmt: "General", font: {name:"Leelawadee",size:10.0,bold:false}, align: {h:"center",v:"center",wrap:false} },
  { addr: "B26", value: "ค่าแห่งลิขสิทธิ์  ฯลฯ  ตามมาตรา 40 (3)", numFmt: "General", font: {name:"Leelawadee",size:10.0,bold:false}, align: {h:null,v:"center",wrap:false} },
  { addr: "A27", value: "4.", numFmt: "General", font: {name:"Leelawadee",size:10.0,bold:false}, align: {h:"center",v:"center",wrap:false} },
  { addr: "B27", value: "(ก) ค่าดอกเบี้ย ฯลฯ  ตามมาตรา 40 (4) (ก)", numFmt: "General", font: {name:"Leelawadee",size:10.0,bold:false}, align: {h:null,v:"center",wrap:false} },
  { addr: "B28", value: "(ข) เงินปันผล ส่วนแบ่งของกำไร ฯลฯ ตามมาตรา 40 (4) (ข)", numFmt: "General", font: {name:"Leelawadee",size:10.0,bold:false}, align: {h:null,v:"center",wrap:false} },
  { addr: "C29", value: "(1) กรณีผู้ด้รับเงินปันผลได้รับเครดิตภาษี โดยจ่ายจาก", numFmt: "General", font: {name:"Leelawadee",size:10.0,bold:false}, align: {h:null,v:"center",wrap:false} },
  { addr: "C30", value: "กำไรสุทธิของกิจการที่ต้องเสียภาษีเงินได้นิติบุคคลในอัตราดังนี้", numFmt: "General", font: {name:"Leelawadee",size:10.0,bold:false}, align: {h:null,v:"center",wrap:false} },
  { addr: "D31", value: "(1.1) อัตราร้อยละ 30 ของกำไรสุทธิ", numFmt: "General", font: {name:"Leelawadee",size:10.0,bold:false}, align: {h:null,v:"center",wrap:false} },
  { addr: "D32", value: "(1.2) อัตราร้อยละ 25 ของกำไรสุทธิ", numFmt: "General", font: {name:"Leelawadee",size:10.0,bold:false}, align: {h:null,v:"center",wrap:false} },
  { addr: "D33", value: "(1.3) อัตราร้อยละ 20 ของกำไรสุทธิ", numFmt: "General", font: {name:"Leelawadee",size:10.0,bold:false}, align: {h:null,v:"center",wrap:false} },
  { addr: "D34", value: "(1.4) อัตราอื่น ๆ ( ระบุ )", numFmt: "General", font: {name:"Leelawadee",size:10.0,bold:false}, align: {h:null,v:"center",wrap:false} },
  { addr: "I34", value: "ของกำไรสุทธิ", numFmt: "General", font: {name:"Leelawadee",size:10.0,bold:false}, align: {h:null,v:"center",wrap:false} },
  { addr: "C35", value: "(2) กิจการที่ได้รับยกเว้นภาษีเงินได้นิติบุคคลซึ่ง ผู้รับเงินปันผลไม่ได้รับเครดิตภาษี", numFmt: "General", font: {name:"Leelawadee",size:10.0,bold:false}, align: {h:null,v:"center",wrap:false} },
  { addr: "D36", value: "(2.1) กำไรสุทธิของกิจการที่ได้รับยกเว้นภาษีเงินได้นิติบุคคล", numFmt: "General", font: {name:"Leelawadee",size:10.0,bold:false}, align: {h:null,v:"center",wrap:false} },
  { addr: "D37", value: "(2.2) เงินปันผลหรือเงินส่วนแบ่งของกำไรที่ได้รับยกเว้นไม่ต้องนำมารวม", numFmt: "General", font: {name:"Leelawadee",size:10.0,bold:false}, align: {h:null,v:"center",wrap:false} },
  { addr: "E38", value: "คำนวณเป็นรายได้เพื่อเสียภาษีนิติบุคคล", numFmt: "General", font: {name:"Leelawadee",size:10.0,bold:false}, align: {h:null,v:"center",wrap:false} },
  { addr: "D39", value: "(2.3) กำไรสุทธิส่วนที่ได้หักผลขาดทุนสุทธิยกมาไม่เกิน 5 ปี", numFmt: "General", font: {name:"Leelawadee",size:10.0,bold:false}, align: {h:null,v:"center",wrap:false} },
  { addr: "E40", value: "ก่อนรอบระยะเวลาบัญชีปัจจุบัน", numFmt: "General", font: {name:"Leelawadee",size:10.0,bold:false}, align: {h:null,v:"center",wrap:false} },
  { addr: "D41", value: "(2.4) กำไรที่รับรู้ทางบัญชีโดยวิธีส่วนได้เสีย (equity method)", numFmt: "General", font: {name:"Leelawadee",size:10.0,bold:false}, align: {h:null,v:"center",wrap:false} },
  { addr: "D42", value: "(2.5) อัตราอื่น ๆ ( ระบุ )", numFmt: "General", font: {name:"Leelawadee",size:10.0,bold:false}, align: {h:null,v:"center",wrap:false} },
  { addr: "A43", value: "5.", numFmt: "General", font: {name:"Leelawadee",size:10.0,bold:false}, align: {h:"center",v:"center",wrap:false} },
  { addr: "B43", value: "การจ่ายเงินได้ที่ต้องหักภาษี ณ. ที่จ่าย ตามคำสั่งกรมสรรพากรที่ออกตาม", numFmt: "General", font: {name:"Leelawadee",size:10.0,bold:false}, align: {h:null,v:"center",wrap:false} },
  { addr: "B44", value: "มาตรา 3 เตรส เช่น รางวัล ส่วนลดหรือประโยชน์ใดๆ เนื่องจากการส่งเสริมการขาย", numFmt: "General", font: {name:"Leelawadee",size:10.0,bold:false}, align: {h:null,v:"center",wrap:false} },
  { addr: "B45", value: "รางวัลในการประกวด การแข่งขัน การชิงโชค ค่าแสดงของนักแสดงสาธารณะ", numFmt: "General", font: {name:"Leelawadee",size:10.0,bold:false}, align: {h:null,v:"center",wrap:false} },
  { addr: "B46", value: "ค่าบริการ ค่าขนส่ง ค่าจ้างทำของ ค่าจ้างโฆษณา ค่าเช่า ค่าเบี้ยประกันวินาศภัย ฯลฯ", numFmt: "General", font: {name:"Leelawadee",size:10.0,bold:false}, align: {h:null,v:"center",wrap:false} },
  { addr: "A47", value: "6.", numFmt: "General", font: {name:"Leelawadee",size:10.0,bold:false}, align: {h:"center",v:"center",wrap:false} },
  { addr: "B47", value: "อื่นๆ(ระบุ)", numFmt: "General", font: {name:"Leelawadee",size:10.0,bold:false}, align: {h:null,v:"center",wrap:false} },
  { addr: "J49", value: "รวมเงินที่จ่าย และ ภาษีที่นำส่ง", numFmt: "General", font: {name:"Leelawadee",size:10.0,bold:false}, align: {h:null,v:"center",wrap:false} },
  { addr: "O49", formula: "SUM(O24:P48)", numFmt: "#,##0.00_ ;[Red]\\-\\ #,##0.00_ ;", font: {name:"Leelawadee",size:10.0,bold:false}, align: {h:null,v:"center",wrap:false} },
  { addr: "Q49", formula: "SUM(Q24:R48)", numFmt: "#,##0.00_ ;[Red]\\-\\ #,##0.00_ ;", font: {name:"Leelawadee",size:10.0,bold:false}, align: {h:null,v:"center",wrap:false} },
  { addr: "A51", value: "รวมเงินภาษีที่นำส่ง (ตัวอักษร)", numFmt: "General", font: {name:"Leelawadee",size:10.0,bold:false}, align: {h:"centerContinuous",v:"center",wrap:false} },
  { addr: "I51", formula: "CONCATENATE(\"-- \",BAHTTEXT(Q49),\" --\")", numFmt: "General", font: {name:"Leelawadee",size:11.0,bold:false}, align: {h:null,v:"center",wrap:false} },
  { addr: "B53", value: "เงินสะสมจ่ายเข้ากองทุนสำรองเลี้ยงชีพ ใบอนุญาตเลขที่", numFmt: "General", font: {name:"Leelawadee",size:10.0,bold:false}, align: {h:"right",v:"center",wrap:false} },
  { addr: "J53", value: "00000000", numFmt: "General", font: {name:"Leelawadee",size:10.0,bold:false}, align: {h:"center",v:"center",wrap:false} },
  { addr: "N53", value: "จำนวนเงิน", numFmt: "General", font: {name:"Leelawadee",size:10.0,bold:false}, align: {h:"right",v:"center",wrap:false} },
  { addr: "P53", value: 10000, numFmt: "#,##0.00", font: {name:"Leelawadee",size:10.0,bold:false}, align: {h:"center",v:"center",wrap:false} },
  { addr: "R53", value: "บาท", numFmt: "General", font: {name:"Leelawadee",size:10.0,bold:false}, align: {h:"left",v:"center",wrap:false} },
  { addr: "C54", value: "เงินสมทบจ่ายเข้ากองทุนประกันสังคม จำนวน ", numFmt: "General", font: {name:"Leelawadee",size:10.0,bold:false}, align: {h:"right",v:"center",wrap:false} },
  { addr: "J54", value: 9000, numFmt: "#,##0.00", font: {name:"Leelawadee",size:10.0,bold:false}, align: {h:"center",v:"center",wrap:false} },
  { addr: "L54", value: "บาท", numFmt: "General", font: {name:"Leelawadee",size:10.0,bold:false}, align: {h:null,v:"center",wrap:false} },
  { addr: "E55", value: "เลขที่บัญชีนายจ้าง", numFmt: "General", font: {name:"Leelawadee",size:10.0,bold:false}, align: {h:null,v:"center",wrap:false} },
  { addr: "G55", value: "0-0000000-0", numFmt: "General", font: {name:"Leelawadee",size:10.0,bold:false}, align: {h:"left",v:"center",wrap:false} },
  { addr: "O55", value: "เลขที่บัตรประกันสังคม ของผู้ถูกหักภาษี ณ ที่จ่าย", numFmt: "General", font: {name:"Leelawadee",size:10.0,bold:false}, align: {h:"right",v:"center",wrap:false} },
  { addr: "P55", value: "0000000000000", numFmt: "0", font: {name:"Leelawadee",size:10.0,bold:false}, align: {h:"left",v:"center",wrap:false} },
  { addr: "A56", value: "ผู้จ่ายเงิน", numFmt: "General", font: {name:"Leelawadee",size:10.0,bold:false}, align: {h:null,v:null,wrap:false} },
  { addr: "G56", value: "ขอรับรองว่าข้อความและตัวเลขดังกล่าวข้างต้น ถูกต้องตรงกับความจริงทุกประการ", numFmt: "General", font: {name:"Leelawadee",size:10.0,bold:false}, align: {h:null,v:null,wrap:false} },
  { addr: "B57", value: "หักภาษี  ณ  ที่จ่าย", numFmt: "General", font: {name:"Leelawadee",size:10.0,bold:false}, align: {h:null,v:"center",wrap:false} },
  { addr: "B58", value: "ออกภาษีให้ตลอดไป", numFmt: "General", font: {name:"Leelawadee",size:10.0,bold:false}, align: {h:null,v:"center",wrap:false} },
  { addr: "B59", value: "ออกภาษีให้ครั้งเดียว", numFmt: "General", font: {name:"Leelawadee",size:10.0,bold:false}, align: {h:null,v:"center",wrap:false} },
  { addr: "F59", value: "ลงชื่อ", numFmt: "General", font: {name:"Leelawadee",size:10.0,bold:false}, align: {h:"right",v:"center",wrap:false} },
  { addr: "L59", value: "ผู้มีหน้าที่หักภาษี ณ ที่จ่าย", numFmt: "General", font: {name:"Leelawadee",size:10.0,bold:false}, align: {h:null,v:"center",wrap:false} },
  { addr: "B60", value: "อื่นๆ (ระบุ)", numFmt: "General", font: {name:"Leelawadee",size:10.0,bold:false}, align: {h:null,v:"center",wrap:false} },
  { addr: "G60", value: new Date(2025,7,18), numFmt: "[$-1870000]d\\-ดดดด\\-yyyy;@", font: {name:"Leelawadee",size:10.0,bold:false}, align: {h:"center",v:"center",wrap:false} },
  { addr: "L60", value: "วัน เดือน ปี  ที่ออกหนังสือรับรองฯ", numFmt: "General", font: {name:"Leelawadee",size:10.0,bold:false}, align: {h:null,v:"center",wrap:false} },
  { addr: "A62", value: " คำเตือน", numFmt: "General", font: {name:"Leelawadee",size:8.0,bold:true}, align: {h:null,v:null,wrap:false} },
  { addr: "D62", value: "ผู้มีหน้าที่ออกหนังสือรับรองการหักภาษี ณ. ที่จ่าย  ", numFmt: "General", font: {name:"Leelawadee",size:8.0,bold:false}, align: {h:null,v:null,wrap:false} },
  { addr: "K62", value: "หมายเหตุ เลขประจำตัวผู้เสียภาษีอากร (13 หลัก)* หมายถึง", numFmt: "General", font: {name:"Leelawadee",size:8.0,bold:true}, align: {h:"left",v:null,wrap:false} },
  { addr: "D63", value: "ฝ่าฝืนไม่ปฏิบัติตามมาตรา  50  ทวิ  แห่งประมวลรัษฎากร", numFmt: "General", font: {name:"Leelawadee",size:8.0,bold:false}, align: {h:null,v:null,wrap:false} },
  { addr: "K63", value: "1. กรณีบุคคลธรรมดาไทย ให้ใช้เลขประจำตัวประชาชนของกรมการปกครอง", numFmt: "General", font: {name:"Leelawadee",size:8.0,bold:false}, align: {h:"left",v:null,wrap:false} },
  { addr: "D64", value: "ต้องรับโทษทางอาญา  ตามมาตรา  35  แห่งประมวลรัษฎากร", numFmt: "General", font: {name:"Leelawadee",size:8.0,bold:false}, align: {h:null,v:null,wrap:false} },
  { addr: "K64", value: "2. กรณีนิติบุคคล ให้ใช้เลขทะเบียนนิติบุคคลของกรมพัฒนาธุรกิจการค้า", numFmt: "General", font: {name:"Leelawadee",size:8.0,bold:false}, align: {h:"left",v:null,wrap:false} },
  { addr: "K65", value: "3. กรณีอื่น ๆ นอกเหนือจาก 1. และ 2. ให้ใช้เลขประจำตัวผู้เสียภาษีอากร (13 หลัก) ", numFmt: "General", font: {name:"Leelawadee",size:8.0,bold:false}, align: {h:"left",v:null,wrap:false} },
];

const BORDERS = [
  { addr: "A3", sides: {top:"thin",left:"thin"} },
  { addr: "B3", sides: {top:"thin"} },
  { addr: "C3", sides: {top:"thin"} },
  { addr: "D3", sides: {top:"thin"} },
  { addr: "E3", sides: {top:"thin"} },
  { addr: "F3", sides: {top:"thin"} },
  { addr: "G3", sides: {top:"thin"} },
  { addr: "H3", sides: {top:"thin"} },
  { addr: "I3", sides: {top:"thin"} },
  { addr: "J3", sides: {top:"thin"} },
  { addr: "K3", sides: {top:"thin"} },
  { addr: "L3", sides: {top:"thin"} },
  { addr: "M3", sides: {top:"thin"} },
  { addr: "N3", sides: {top:"thin"} },
  { addr: "O3", sides: {top:"thin"} },
  { addr: "P3", sides: {top:"thin"} },
  { addr: "Q3", sides: {top:"thin",right:"thin"} },
  { addr: "R3", sides: {top:"thin",right:"thin"} },
  { addr: "A4", sides: {bottom:"thin",left:"thin"} },
  { addr: "B4", sides: {bottom:"thin"} },
  { addr: "C4", sides: {bottom:"thin"} },
  { addr: "D4", sides: {bottom:"thin"} },
  { addr: "E4", sides: {bottom:"thin"} },
  { addr: "F4", sides: {bottom:"thin"} },
  { addr: "G4", sides: {bottom:"thin"} },
  { addr: "H4", sides: {bottom:"thin"} },
  { addr: "I4", sides: {bottom:"thin"} },
  { addr: "J4", sides: {bottom:"thin"} },
  { addr: "K4", sides: {bottom:"thin"} },
  { addr: "L4", sides: {bottom:"thin"} },
  { addr: "M4", sides: {bottom:"thin"} },
  { addr: "N4", sides: {bottom:"thin"} },
  { addr: "O4", sides: {bottom:"thin"} },
  { addr: "P4", sides: {bottom:"thin"} },
  { addr: "Q4", sides: {bottom:"thin",right:"thin"} },
  { addr: "R4", sides: {bottom:"thin",right:"thin"} },
  { addr: "A6", sides: {top:"thin",left:"thin"} },
  { addr: "B6", sides: {top:"thin"} },
  { addr: "C6", sides: {top:"thin"} },
  { addr: "D6", sides: {top:"thin"} },
  { addr: "E6", sides: {top:"thin"} },
  { addr: "F6", sides: {top:"thin"} },
  { addr: "G6", sides: {top:"thin"} },
  { addr: "H6", sides: {top:"thin"} },
  { addr: "I6", sides: {top:"thin"} },
  { addr: "J6", sides: {top:"thin"} },
  { addr: "K6", sides: {top:"thin"} },
  { addr: "L6", sides: {top:"thin"} },
  { addr: "M6", sides: {top:"thin"} },
  { addr: "N6", sides: {top:"thin"} },
  { addr: "O6", sides: {top:"thin"} },
  { addr: "P6", sides: {top:"thin",right:"thin"} },
  { addr: "Q6", sides: {top:"thin"} },
  { addr: "R6", sides: {top:"thin",right:"thin"} },
  { addr: "A7", sides: {left:"thin"} },
  { addr: "C7", sides: {bottom:"dotted"} },
  { addr: "D7", sides: {bottom:"dotted"} },
  { addr: "E7", sides: {bottom:"dotted"} },
  { addr: "F7", sides: {bottom:"dotted"} },
  { addr: "G7", sides: {bottom:"dotted"} },
  { addr: "H7", sides: {bottom:"dotted"} },
  { addr: "I7", sides: {bottom:"dotted"} },
  { addr: "J7", sides: {bottom:"dotted"} },
  { addr: "K7", sides: {bottom:"dotted"} },
  { addr: "P7", sides: {right:"thin"} },
  { addr: "R7", sides: {right:"thin"} },
  { addr: "A8", sides: {left:"thin"} },
  { addr: "R8", sides: {right:"thin"} },
  { addr: "A9", sides: {left:"thin"} },
  { addr: "C9", sides: {bottom:"dotted",right:"thin"} },
  { addr: "D9", sides: {bottom:"dotted"} },
  { addr: "E9", sides: {bottom:"dotted"} },
  { addr: "F9", sides: {bottom:"dotted"} },
  { addr: "G9", sides: {bottom:"dotted"} },
  { addr: "H9", sides: {bottom:"dotted"} },
  { addr: "I9", sides: {bottom:"dotted"} },
  { addr: "J9", sides: {bottom:"dotted"} },
  { addr: "K9", sides: {bottom:"dotted"} },
  { addr: "L9", sides: {bottom:"dotted"} },
  { addr: "M9", sides: {bottom:"dotted"} },
  { addr: "N9", sides: {bottom:"dotted"} },
  { addr: "O9", sides: {bottom:"dotted"} },
  { addr: "P9", sides: {bottom:"dotted"} },
  { addr: "Q9", sides: {bottom:"dotted"} },
  { addr: "R9", sides: {bottom:"dotted",right:"thin"} },
  { addr: "A10", sides: {bottom:"thin",left:"thin"} },
  { addr: "B10", sides: {bottom:"thin"} },
  { addr: "C10", sides: {bottom:"thin"} },
  { addr: "D10", sides: {bottom:"thin"} },
  { addr: "E10", sides: {bottom:"thin"} },
  { addr: "F10", sides: {bottom:"thin"} },
  { addr: "G10", sides: {bottom:"thin"} },
  { addr: "H10", sides: {bottom:"thin"} },
  { addr: "I10", sides: {bottom:"thin"} },
  { addr: "J10", sides: {bottom:"thin"} },
  { addr: "K10", sides: {bottom:"thin"} },
  { addr: "L10", sides: {bottom:"thin"} },
  { addr: "M10", sides: {bottom:"thin"} },
  { addr: "N10", sides: {bottom:"thin"} },
  { addr: "O10", sides: {bottom:"thin"} },
  { addr: "P10", sides: {bottom:"thin"} },
  { addr: "Q10", sides: {bottom:"thin"} },
  { addr: "R10", sides: {bottom:"thin",right:"thin"} },
  { addr: "A12", sides: {top:"thin",left:"thin"} },
  { addr: "B12", sides: {top:"thin"} },
  { addr: "C12", sides: {top:"thin"} },
  { addr: "D12", sides: {top:"thin"} },
  { addr: "E12", sides: {top:"thin"} },
  { addr: "F12", sides: {top:"thin"} },
  { addr: "G12", sides: {top:"thin"} },
  { addr: "H12", sides: {top:"thin"} },
  { addr: "I12", sides: {top:"thin"} },
  { addr: "J12", sides: {top:"thin"} },
  { addr: "K12", sides: {top:"thin"} },
  { addr: "L12", sides: {top:"thin"} },
  { addr: "M12", sides: {top:"thin"} },
  { addr: "N12", sides: {top:"thin"} },
  { addr: "O12", sides: {top:"thin"} },
  { addr: "P12", sides: {top:"thin",right:"thin"} },
  { addr: "Q12", sides: {top:"thin"} },
  { addr: "R12", sides: {top:"thin",right:"thin"} },
  { addr: "A13", sides: {left:"thin"} },
  { addr: "C13", sides: {bottom:"dotted"} },
  { addr: "D13", sides: {bottom:"dotted"} },
  { addr: "E13", sides: {bottom:"dotted"} },
  { addr: "F13", sides: {bottom:"dotted"} },
  { addr: "G13", sides: {bottom:"dotted"} },
  { addr: "H13", sides: {bottom:"dotted"} },
  { addr: "I13", sides: {bottom:"dotted"} },
  { addr: "J13", sides: {bottom:"dotted"} },
  { addr: "K13", sides: {bottom:"dotted"} },
  { addr: "P13", sides: {right:"thin"} },
  { addr: "R13", sides: {right:"thin"} },
  { addr: "A14", sides: {left:"thin"} },
  { addr: "R14", sides: {right:"thin"} },
  { addr: "A15", sides: {left:"thin"} },
  { addr: "C15", sides: {bottom:"dotted",right:"thin"} },
  { addr: "D15", sides: {bottom:"dotted"} },
  { addr: "E15", sides: {bottom:"dotted"} },
  { addr: "F15", sides: {bottom:"dotted"} },
  { addr: "G15", sides: {bottom:"dotted"} },
  { addr: "H15", sides: {bottom:"dotted"} },
  { addr: "I15", sides: {bottom:"dotted"} },
  { addr: "J15", sides: {bottom:"dotted"} },
  { addr: "K15", sides: {bottom:"dotted"} },
  { addr: "L15", sides: {bottom:"dotted"} },
  { addr: "M15", sides: {bottom:"dotted"} },
  { addr: "N15", sides: {bottom:"dotted"} },
  { addr: "O15", sides: {bottom:"dotted"} },
  { addr: "P15", sides: {bottom:"dotted"} },
  { addr: "Q15", sides: {bottom:"dotted"} },
  { addr: "R15", sides: {bottom:"dotted",right:"thin"} },
  { addr: "A16", sides: {left:"thin"} },
  { addr: "R16", sides: {right:"thin"} },
  { addr: "A17", sides: {left:"thin"} },
  { addr: "D17", sides: {top:"thin",bottom:"thick",left:"thin",right:"thick"} },
  { addr: "E17", sides: {top:"thin",bottom:"thick",right:"thick"} },
  { addr: "H17", sides: {top:"medium",bottom:"medium",left:"medium",right:"medium"} },
  { addr: "J17", sides: {top:"medium",bottom:"medium",left:"medium",right:"medium"} },
  { addr: "M17", sides: {top:"medium",bottom:"medium",left:"medium",right:"medium"} },
  { addr: "O17", sides: {top:"medium",bottom:"medium",left:"medium",right:"medium"} },
  { addr: "R17", sides: {right:"thin"} },
  { addr: "A18", sides: {bottom:"thin",left:"thin"} },
  { addr: "R18", sides: {right:"thin"} },
  { addr: "A19", sides: {left:"thin"} },
  { addr: "H19", sides: {top:"medium",bottom:"medium",left:"medium",right:"medium"} },
  { addr: "J19", sides: {top:"medium",bottom:"medium",left:"medium",right:"medium"} },
  { addr: "M19", sides: {top:"medium",bottom:"medium",left:"medium",right:"medium"} },
  { addr: "R19", sides: {right:"thin"} },
  { addr: "A20", sides: {bottom:"thin",left:"thin"} },
  { addr: "B20", sides: {bottom:"thin"} },
  { addr: "C20", sides: {bottom:"thin"} },
  { addr: "D20", sides: {bottom:"thin"} },
  { addr: "E20", sides: {bottom:"thin"} },
  { addr: "F20", sides: {bottom:"thin"} },
  { addr: "G20", sides: {bottom:"thin"} },
  { addr: "H20", sides: {bottom:"thin"} },
  { addr: "I20", sides: {bottom:"thin"} },
  { addr: "J20", sides: {bottom:"thin"} },
  { addr: "K20", sides: {bottom:"thin"} },
  { addr: "L20", sides: {bottom:"thin"} },
  { addr: "M20", sides: {bottom:"thin"} },
  { addr: "N20", sides: {bottom:"thin"} },
  { addr: "O20", sides: {bottom:"thin"} },
  { addr: "P20", sides: {bottom:"thin"} },
  { addr: "Q20", sides: {bottom:"thin"} },
  { addr: "R20", sides: {bottom:"thin",right:"thin"} },
  { addr: "A22", sides: {top:"thin",bottom:"thin",left:"thin",right:"thin"} },
  { addr: "B22", sides: {top:"thin"} },
  { addr: "C22", sides: {top:"thin"} },
  { addr: "D22", sides: {top:"thin"} },
  { addr: "E22", sides: {top:"thin"} },
  { addr: "F22", sides: {top:"thin"} },
  { addr: "G22", sides: {top:"thin"} },
  { addr: "H22", sides: {top:"thin"} },
  { addr: "I22", sides: {top:"thin"} },
  { addr: "J22", sides: {top:"thin"} },
  { addr: "K22", sides: {top:"thin"} },
  { addr: "L22", sides: {top:"thin",right:"thin"} },
  { addr: "M22", sides: {top:"thin",left:"thin"} },
  { addr: "N22", sides: {top:"thin",right:"thin"} },
  { addr: "O22", sides: {top:"thin",bottom:"thin",left:"thin",right:"thin"} },
  { addr: "P22", sides: {top:"thin",right:"thin"} },
  { addr: "Q22", sides: {top:"thin",left:"thin"} },
  { addr: "R22", sides: {top:"thin",right:"thin"} },
  { addr: "A23", sides: {bottom:"thin",left:"thin"} },
  { addr: "B23", sides: {bottom:"thin"} },
  { addr: "C23", sides: {bottom:"thin"} },
  { addr: "D23", sides: {bottom:"thin"} },
  { addr: "E23", sides: {bottom:"thin"} },
  { addr: "F23", sides: {bottom:"thin"} },
  { addr: "G23", sides: {bottom:"thin"} },
  { addr: "H23", sides: {bottom:"thin"} },
  { addr: "I23", sides: {bottom:"thin"} },
  { addr: "J23", sides: {bottom:"thin"} },
  { addr: "K23", sides: {bottom:"thin"} },
  { addr: "L23", sides: {bottom:"thin",right:"thin"} },
  { addr: "M23", sides: {bottom:"thin",left:"thin"} },
  { addr: "N23", sides: {bottom:"thin",right:"thin"} },
  { addr: "O23", sides: {bottom:"thin",left:"thin"} },
  { addr: "P23", sides: {bottom:"thin",right:"thin"} },
  { addr: "Q23", sides: {bottom:"thin",left:"thin"} },
  { addr: "R23", sides: {bottom:"thin",right:"thin"} },
  { addr: "A24", sides: {top:"thin",left:"thin"} },
  { addr: "L24", sides: {top:"thin",right:"thin"} },
  { addr: "M24", sides: {top:"thin",left:"thin",right:"thin"} },
  { addr: "N24", sides: {top:"thin",right:"thin"} },
  { addr: "O24", sides: {top:"thin",left:"thin",right:"thin"} },
  { addr: "P24", sides: {top:"thin",right:"thin"} },
  { addr: "Q24", sides: {top:"thin",left:"thin",right:"thin"} },
  { addr: "R24", sides: {top:"thin",right:"thin"} },
  { addr: "A25", sides: {left:"thin"} },
  { addr: "L25", sides: {right:"thin"} },
  { addr: "M25", sides: {left:"thin",right:"thin"} },
  { addr: "N25", sides: {right:"thin"} },
  { addr: "O25", sides: {left:"thin",right:"thin"} },
  { addr: "P25", sides: {right:"thin"} },
  { addr: "Q25", sides: {left:"thin",right:"thin"} },
  { addr: "R25", sides: {right:"thin"} },
  { addr: "A26", sides: {left:"thin"} },
  { addr: "L26", sides: {right:"thin"} },
  { addr: "M26", sides: {left:"thin",right:"thin"} },
  { addr: "N26", sides: {right:"thin"} },
  { addr: "O26", sides: {left:"thin",right:"thin"} },
  { addr: "P26", sides: {right:"thin"} },
  { addr: "Q26", sides: {left:"thin",right:"thin"} },
  { addr: "R26", sides: {right:"thin"} },
  { addr: "A27", sides: {left:"thin"} },
  { addr: "L27", sides: {right:"thin"} },
  { addr: "M27", sides: {left:"thin",right:"thin"} },
  { addr: "N27", sides: {right:"thin"} },
  { addr: "O27", sides: {left:"thin",right:"thin"} },
  { addr: "P27", sides: {right:"thin"} },
  { addr: "Q27", sides: {left:"thin",right:"thin"} },
  { addr: "R27", sides: {right:"thin"} },
  { addr: "A28", sides: {left:"thin"} },
  { addr: "L28", sides: {right:"thin"} },
  { addr: "M28", sides: {left:"thin",right:"thin"} },
  { addr: "N28", sides: {right:"thin"} },
  { addr: "O28", sides: {left:"thin",right:"thin"} },
  { addr: "P28", sides: {right:"thin"} },
  { addr: "Q28", sides: {left:"thin",right:"thin"} },
  { addr: "R28", sides: {right:"thin"} },
  { addr: "A29", sides: {left:"thin"} },
  { addr: "L29", sides: {right:"thin"} },
  { addr: "M29", sides: {left:"thin",right:"thin"} },
  { addr: "N29", sides: {right:"thin"} },
  { addr: "O29", sides: {left:"thin",right:"thin"} },
  { addr: "P29", sides: {right:"thin"} },
  { addr: "Q29", sides: {left:"thin",right:"thin"} },
  { addr: "R29", sides: {right:"thin"} },
  { addr: "A30", sides: {left:"thin"} },
  { addr: "L30", sides: {right:"thin"} },
  { addr: "M30", sides: {left:"thin",right:"thin"} },
  { addr: "N30", sides: {right:"thin"} },
  { addr: "O30", sides: {left:"thin",right:"thin"} },
  { addr: "P30", sides: {right:"thin"} },
  { addr: "Q30", sides: {left:"thin",right:"thin"} },
  { addr: "R30", sides: {right:"thin"} },
  { addr: "A31", sides: {left:"thin"} },
  { addr: "L31", sides: {right:"thin"} },
  { addr: "M31", sides: {left:"thin",right:"thin"} },
  { addr: "N31", sides: {right:"thin"} },
  { addr: "O31", sides: {left:"thin",right:"thin"} },
  { addr: "P31", sides: {right:"thin"} },
  { addr: "Q31", sides: {left:"thin",right:"thin"} },
  { addr: "R31", sides: {right:"thin"} },
  { addr: "A32", sides: {left:"thin"} },
  { addr: "L32", sides: {right:"thin"} },
  { addr: "M32", sides: {left:"thin",right:"thin"} },
  { addr: "N32", sides: {right:"thin"} },
  { addr: "O32", sides: {left:"thin",right:"thin"} },
  { addr: "P32", sides: {right:"thin"} },
  { addr: "Q32", sides: {left:"thin",right:"thin"} },
  { addr: "R32", sides: {right:"thin"} },
  { addr: "A33", sides: {left:"thin"} },
  { addr: "L33", sides: {right:"thin"} },
  { addr: "M33", sides: {left:"thin",right:"thin"} },
  { addr: "N33", sides: {right:"thin"} },
  { addr: "O33", sides: {left:"thin",right:"thin"} },
  { addr: "P33", sides: {right:"thin"} },
  { addr: "Q33", sides: {left:"thin",right:"thin"} },
  { addr: "R33", sides: {right:"thin"} },
  { addr: "A34", sides: {left:"thin"} },
  { addr: "G34", sides: {bottom:"dashed"} },
  { addr: "H34", sides: {bottom:"dashed"} },
  { addr: "L34", sides: {right:"thin"} },
  { addr: "M34", sides: {left:"thin",right:"thin"} },
  { addr: "N34", sides: {right:"thin"} },
  { addr: "O34", sides: {left:"thin",right:"thin"} },
  { addr: "P34", sides: {right:"thin"} },
  { addr: "Q34", sides: {left:"thin",right:"thin"} },
  { addr: "R34", sides: {right:"thin"} },
  { addr: "A35", sides: {left:"thin"} },
  { addr: "L35", sides: {right:"thin"} },
  { addr: "M35", sides: {left:"thin",right:"thin"} },
  { addr: "N35", sides: {right:"thin"} },
  { addr: "O35", sides: {left:"thin",right:"thin"} },
  { addr: "P35", sides: {right:"thin"} },
  { addr: "Q35", sides: {left:"thin",right:"thin"} },
  { addr: "R35", sides: {right:"thin"} },
  { addr: "A36", sides: {left:"thin"} },
  { addr: "L36", sides: {right:"thin"} },
  { addr: "M36", sides: {left:"thin",right:"thin"} },
  { addr: "N36", sides: {right:"thin"} },
  { addr: "O36", sides: {left:"thin",right:"thin"} },
  { addr: "P36", sides: {right:"thin"} },
  { addr: "Q36", sides: {left:"thin",right:"thin"} },
  { addr: "R36", sides: {right:"thin"} },
  { addr: "A37", sides: {left:"thin"} },
  { addr: "L37", sides: {right:"thin"} },
  { addr: "M37", sides: {left:"thin",right:"thin"} },
  { addr: "N37", sides: {right:"thin"} },
  { addr: "O37", sides: {left:"thin",right:"thin"} },
  { addr: "P37", sides: {right:"thin"} },
  { addr: "Q37", sides: {left:"thin",right:"thin"} },
  { addr: "R37", sides: {right:"thin"} },
  { addr: "A38", sides: {left:"thin"} },
  { addr: "L38", sides: {right:"thin"} },
  { addr: "M38", sides: {left:"thin",right:"thin"} },
  { addr: "N38", sides: {right:"thin"} },
  { addr: "O38", sides: {left:"thin",right:"thin"} },
  { addr: "P38", sides: {right:"thin"} },
  { addr: "Q38", sides: {left:"thin",right:"thin"} },
  { addr: "R38", sides: {right:"thin"} },
  { addr: "A39", sides: {left:"thin"} },
  { addr: "L39", sides: {right:"thin"} },
  { addr: "M39", sides: {left:"thin",right:"thin"} },
  { addr: "N39", sides: {right:"thin"} },
  { addr: "O39", sides: {left:"thin",right:"thin"} },
  { addr: "P39", sides: {right:"thin"} },
  { addr: "Q39", sides: {left:"thin",right:"thin"} },
  { addr: "R39", sides: {right:"thin"} },
  { addr: "A40", sides: {left:"thin"} },
  { addr: "L40", sides: {right:"thin"} },
  { addr: "M40", sides: {left:"thin",right:"thin"} },
  { addr: "N40", sides: {right:"thin"} },
  { addr: "O40", sides: {left:"thin",right:"thin"} },
  { addr: "P40", sides: {right:"thin"} },
  { addr: "Q40", sides: {left:"thin",right:"thin"} },
  { addr: "R40", sides: {right:"thin"} },
  { addr: "A41", sides: {left:"thin"} },
  { addr: "L41", sides: {right:"thin"} },
  { addr: "M41", sides: {left:"thin",right:"thin"} },
  { addr: "N41", sides: {right:"thin"} },
  { addr: "O41", sides: {left:"thin",right:"thin"} },
  { addr: "P41", sides: {right:"thin"} },
  { addr: "Q41", sides: {left:"thin",right:"thin"} },
  { addr: "R41", sides: {right:"thin"} },
  { addr: "A42", sides: {left:"thin"} },
  { addr: "G42", sides: {bottom:"dashed"} },
  { addr: "H42", sides: {bottom:"dashed"} },
  { addr: "I42", sides: {bottom:"dashed"} },
  { addr: "J42", sides: {bottom:"dashed"} },
  { addr: "K42", sides: {bottom:"dashed"} },
  { addr: "L42", sides: {right:"thin"} },
  { addr: "M42", sides: {left:"thin",right:"thin"} },
  { addr: "N42", sides: {right:"thin"} },
  { addr: "O42", sides: {left:"thin",right:"thin"} },
  { addr: "P42", sides: {right:"thin"} },
  { addr: "Q42", sides: {left:"thin",right:"thin"} },
  { addr: "R42", sides: {right:"thin"} },
  { addr: "A43", sides: {left:"thin"} },
  { addr: "L43", sides: {right:"thin"} },
  { addr: "M43", sides: {left:"thin",right:"thin"} },
  { addr: "N43", sides: {right:"thin"} },
  { addr: "O43", sides: {left:"thin",right:"thin"} },
  { addr: "P43", sides: {right:"thin"} },
  { addr: "Q43", sides: {left:"thin",right:"thin"} },
  { addr: "R43", sides: {right:"thin"} },
  { addr: "A44", sides: {left:"thin"} },
  { addr: "L44", sides: {right:"thin"} },
  { addr: "M44", sides: {left:"thin",right:"thin"} },
  { addr: "N44", sides: {right:"thin"} },
  { addr: "O44", sides: {left:"thin",right:"thin"} },
  { addr: "P44", sides: {right:"thin"} },
  { addr: "Q44", sides: {left:"thin",right:"thin"} },
  { addr: "R44", sides: {right:"thin"} },
  { addr: "A45", sides: {left:"thin"} },
  { addr: "L45", sides: {right:"thin"} },
  { addr: "M45", sides: {left:"thin",right:"thin"} },
  { addr: "N45", sides: {right:"thin"} },
  { addr: "O45", sides: {left:"thin",right:"thin"} },
  { addr: "P45", sides: {right:"thin"} },
  { addr: "Q45", sides: {left:"thin",right:"thin"} },
  { addr: "R45", sides: {right:"thin"} },
  { addr: "A46", sides: {left:"thin"} },
  { addr: "L46", sides: {right:"thin"} },
  { addr: "M46", sides: {left:"thin",right:"thin"} },
  { addr: "N46", sides: {right:"thin"} },
  { addr: "O46", sides: {left:"thin",right:"thin"} },
  { addr: "P46", sides: {right:"thin"} },
  { addr: "Q46", sides: {left:"thin",right:"thin"} },
  { addr: "R46", sides: {right:"thin"} },
  { addr: "A47", sides: {left:"thin"} },
  { addr: "E47", sides: {bottom:"dashed"} },
  { addr: "F47", sides: {bottom:"dashed"} },
  { addr: "G47", sides: {bottom:"dashed"} },
  { addr: "H47", sides: {bottom:"dashed"} },
  { addr: "I47", sides: {bottom:"dashed"} },
  { addr: "J47", sides: {bottom:"dashed"} },
  { addr: "K47", sides: {bottom:"dashed"} },
  { addr: "L47", sides: {right:"thin"} },
  { addr: "M47", sides: {left:"thin",right:"thin"} },
  { addr: "N47", sides: {right:"thin"} },
  { addr: "O47", sides: {left:"thin",right:"thin"} },
  { addr: "P47", sides: {right:"thin"} },
  { addr: "Q47", sides: {left:"thin",right:"thin"} },
  { addr: "R47", sides: {right:"thin"} },
  { addr: "A48", sides: {bottom:"thin",left:"thin"} },
  { addr: "B48", sides: {bottom:"thin"} },
  { addr: "C48", sides: {bottom:"thin"} },
  { addr: "D48", sides: {bottom:"thin"} },
  { addr: "E48", sides: {bottom:"thin"} },
  { addr: "F48", sides: {bottom:"thin"} },
  { addr: "G48", sides: {bottom:"thin"} },
  { addr: "H48", sides: {bottom:"thin"} },
  { addr: "I48", sides: {bottom:"thin"} },
  { addr: "J48", sides: {bottom:"thin"} },
  { addr: "K48", sides: {bottom:"thin"} },
  { addr: "L48", sides: {bottom:"thin",right:"thin"} },
  { addr: "M48", sides: {bottom:"thin",left:"thin",right:"thin"} },
  { addr: "N48", sides: {bottom:"thin",right:"thin"} },
  { addr: "O48", sides: {bottom:"thin",left:"thin",right:"thin"} },
  { addr: "P48", sides: {bottom:"thin",right:"thin"} },
  { addr: "Q48", sides: {bottom:"thin",left:"thin",right:"thin"} },
  { addr: "R48", sides: {bottom:"thin",right:"thin"} },
  { addr: "A49", sides: {top:"thin",left:"thin"} },
  { addr: "O49", sides: {bottom:"thin",left:"thin",right:"thin"} },
  { addr: "P49", sides: {bottom:"thin",right:"thin"} },
  { addr: "Q49", sides: {bottom:"thin",left:"thin",right:"thin"} },
  { addr: "R49", sides: {bottom:"thin",right:"thin"} },
  { addr: "A50", sides: {left:"thin"} },
  { addr: "R50", sides: {top:"thin",right:"thin"} },
  { addr: "A51", sides: {left:"thin"} },
  { addr: "G51", sides: {top:"medium",bottom:"medium",left:"medium"} },
  { addr: "H51", sides: {top:"medium",bottom:"medium"} },
  { addr: "I51", sides: {top:"medium",bottom:"medium"} },
  { addr: "J51", sides: {top:"medium",bottom:"medium"} },
  { addr: "K51", sides: {top:"medium",bottom:"medium"} },
  { addr: "L51", sides: {top:"medium",bottom:"medium"} },
  { addr: "M51", sides: {top:"medium",bottom:"medium"} },
  { addr: "N51", sides: {top:"medium",bottom:"medium"} },
  { addr: "O51", sides: {top:"medium",bottom:"medium"} },
  { addr: "P51", sides: {top:"medium",bottom:"medium"} },
  { addr: "Q51", sides: {top:"medium",bottom:"medium"} },
  { addr: "R51", sides: {top:"medium",bottom:"medium",right:"medium"} },
  { addr: "A52", sides: {bottom:"thin",left:"thin"} },
  { addr: "R52", sides: {bottom:"thin",right:"thin"} },
  { addr: "A53", sides: {top:"thin",left:"thin"} },
  { addr: "B53", sides: {top:"thin"} },
  { addr: "C53", sides: {top:"thin"} },
  { addr: "D53", sides: {top:"thin"} },
  { addr: "E53", sides: {top:"thin"} },
  { addr: "F53", sides: {top:"thin"} },
  { addr: "G53", sides: {top:"thin"} },
  { addr: "H53", sides: {top:"thin"} },
  { addr: "I53", sides: {top:"thin"} },
  { addr: "J53", sides: {top:"thin",bottom:"hair"} },
  { addr: "K53", sides: {top:"thin",bottom:"hair"} },
  { addr: "L53", sides: {top:"thin"} },
  { addr: "M53", sides: {top:"thin"} },
  { addr: "N53", sides: {top:"thin"} },
  { addr: "O53", sides: {top:"thin"} },
  { addr: "P53", sides: {top:"thin",bottom:"hair"} },
  { addr: "Q53", sides: {top:"thin",bottom:"hair"} },
  { addr: "R53", sides: {top:"thin",right:"thin"} },
  { addr: "A54", sides: {left:"thin"} },
  { addr: "J54", sides: {bottom:"hair"} },
  { addr: "K54", sides: {bottom:"hair"} },
  { addr: "R54", sides: {right:"thin"} },
  { addr: "A55", sides: {bottom:"thin",left:"thin"} },
  { addr: "B55", sides: {bottom:"thin"} },
  { addr: "C55", sides: {bottom:"thin"} },
  { addr: "D55", sides: {bottom:"thin"} },
  { addr: "E55", sides: {bottom:"thin"} },
  { addr: "F55", sides: {bottom:"thin"} },
  { addr: "G55", sides: {bottom:"thin"} },
  { addr: "H55", sides: {bottom:"thin"} },
  { addr: "I55", sides: {bottom:"thin"} },
  { addr: "J55", sides: {bottom:"thin"} },
  { addr: "L55", sides: {bottom:"thin"} },
  { addr: "M55", sides: {bottom:"thin"} },
  { addr: "N55", sides: {bottom:"thin"} },
  { addr: "O55", sides: {bottom:"thin"} },
  { addr: "P55", sides: {bottom:"thin",right:"thin"} },
  { addr: "Q55", sides: {bottom:"thin"} },
  { addr: "R55", sides: {bottom:"thin",right:"thin"} },
  { addr: "A56", sides: {top:"thin",left:"thin"} },
  { addr: "B56", sides: {top:"thin"} },
  { addr: "C56", sides: {top:"thin"} },
  { addr: "D56", sides: {top:"thin"} },
  { addr: "E56", sides: {top:"thin"} },
  { addr: "F56", sides: {top:"thin",left:"thin"} },
  { addr: "G56", sides: {top:"thin"} },
  { addr: "H56", sides: {top:"thin"} },
  { addr: "I56", sides: {top:"thin"} },
  { addr: "J56", sides: {top:"thin"} },
  { addr: "K56", sides: {top:"thin"} },
  { addr: "L56", sides: {top:"thin"} },
  { addr: "M56", sides: {top:"thin"} },
  { addr: "N56", sides: {top:"thin"} },
  { addr: "O56", sides: {top:"thin"} },
  { addr: "P56", sides: {top:"thin"} },
  { addr: "Q56", sides: {top:"thin"} },
  { addr: "R56", sides: {top:"thin",right:"thin"} },
  { addr: "A57", sides: {left:"thin"} },
  { addr: "F57", sides: {left:"thin"} },
  { addr: "R57", sides: {right:"thin"} },
  { addr: "A58", sides: {left:"thin"} },
  { addr: "F58", sides: {left:"thin"} },
  { addr: "R58", sides: {right:"thin"} },
  { addr: "A59", sides: {left:"thin"} },
  { addr: "F59", sides: {left:"thin"} },
  { addr: "G59", sides: {bottom:"dotted"} },
  { addr: "H59", sides: {bottom:"dotted"} },
  { addr: "I59", sides: {bottom:"dotted"} },
  { addr: "J59", sides: {bottom:"dotted"} },
  { addr: "K59", sides: {bottom:"dotted"} },
  { addr: "R59", sides: {right:"thin"} },
  { addr: "A60", sides: {left:"thin"} },
  { addr: "F60", sides: {left:"thin"} },
  { addr: "G60", sides: {top:"dotted",bottom:"dotted"} },
  { addr: "H60", sides: {top:"dotted",bottom:"dotted"} },
  { addr: "I60", sides: {top:"dotted",bottom:"dotted"} },
  { addr: "J60", sides: {top:"dotted",bottom:"dotted"} },
  { addr: "K60", sides: {top:"dotted",bottom:"dotted"} },
  { addr: "R60", sides: {right:"thin"} },
  { addr: "A61", sides: {bottom:"thin",left:"thin"} },
  { addr: "B61", sides: {bottom:"thin"} },
  { addr: "C61", sides: {bottom:"thin"} },
  { addr: "D61", sides: {bottom:"thin"} },
  { addr: "E61", sides: {bottom:"thin"} },
  { addr: "F61", sides: {bottom:"thin",left:"thin"} },
  { addr: "G61", sides: {bottom:"thin"} },
  { addr: "H61", sides: {bottom:"thin"} },
  { addr: "I61", sides: {bottom:"thin"} },
  { addr: "J61", sides: {bottom:"thin"} },
  { addr: "K61", sides: {bottom:"thin"} },
  { addr: "L61", sides: {bottom:"thin"} },
  { addr: "M61", sides: {bottom:"thin"} },
  { addr: "N61", sides: {bottom:"thin"} },
  { addr: "O61", sides: {bottom:"thin"} },
  { addr: "P61", sides: {bottom:"thin"} },
  { addr: "Q61", sides: {bottom:"thin"} },
  { addr: "R61", sides: {bottom:"thin",right:"thin"} },
];

const COL_WIDTHS = {
  "A": 2.7109375,
  "B": 2.28515625,
  "C": 3.28515625,
  "D": 3.85546875,
  "E": 7.7109375,
  "G": 5.7109375,
  "H": 2.7109375,
  "I": 11.7109375,
  "J": 2.7109375,
  "K": 11.7109375,
  "L": 4.7109375,
  "M": 2.7109375,
  "N": 10.7109375,
  "O": 2.7109375,
  "P": 10.7109375,
  "Q": 2.7109375,
  "R": 10.7109375,
};

const ROW_HEIGHTS = {
  3: 18.6,
  4: 15.0,
  5: 5.1,
  6: 15.0,
  7: 21.0,
  9: 21.0,
  11: 5.1,
  12: 15.0,
  13: 21.0,
  15: 21.0,
  16: 13.5,
  17: 15.95,
  18: 6.95,
  19: 15.95,
  20: 6.95,
  21: 5.1,
  22: 12.75,
  23: 12.75,
  24: 12.75,
  25: 12.75,
  26: 12.75,
  27: 12.75,
  28: 12.75,
  29: 12.75,
  30: 12.75,
  31: 12.75,
  32: 12.75,
  33: 12.75,
  34: 12.75,
  35: 12.75,
  36: 12.75,
  37: 12.75,
  38: 12.75,
  39: 12.75,
  40: 12.75,
  41: 12.75,
  42: 12.75,
  43: 12.75,
  44: 12.75,
  45: 12.75,
  46: 12.75,
  47: 12.75,
  48: 9.95,
  49: 15.95,
  50: 12.75,
  51: 20.1,
  52: 12.75,
  53: 13.5,
  54: 12.75,
  55: 12.75,
  56: 12.75,
  57: 14.45,
  58: 14.45,
  59: 14.45,
  60: 14.45,
  61: 12.75,
};

module.exports = { MERGES, CELLS, BORDERS, COL_WIDTHS, ROW_HEIGHTS };
